### ISSUE TITLE
Microsoft LTI Integration with Moodle- Error

### ISSUE THREAD

**Issue by coachsbansal** [microsoft/Learn-LTI#118] opened 2021-03-11 13:39 UTC
I have integrated the Microsoft Learn LTI with Moodle 3.9. After following all steps given in the below documents

- https://github.com/microsoft/Learn-LTI/blob/main/docs/DEPLOYMENT_GUIDE.md
- https://github.com/microsoft/Learn-LTI/blob/main/docs/CONFIGURATION_GUIDE.md
- https://github.com/microsoft/Learn-LTI/blob/main/docs/USER_GUIDE.md#Customize-Review-and-Publish-the-assignment
- https://github.com/microsoft/Learn-LTI/blob/main/docs/USER_GUIDE.md

While trying to access the Microsoft Learn LTI on Moodle Platform, I am getting the below error:

{"Message": "Could not validate request."}

Rechecked the configuration, Cleared history. But the issue still persists.

Kindly suggest some solution

**Comment by leestott** [comment] 2021-03-15 12:01
Hi @coachsbansal 

You don't need to enter the Launch URL as the Target Link URI in the 2 sections.

For the "Could not validate request" error, please make sure that all the fields are correctly filled while registering the tool and filling tool's platform registration page. Also please ensure your service is using https:// with a valid SSL certification

Can you confirm if your using https:// for the tool URL

See 
![Image](https://github.com/microsoft/Learn-LTI/blob/main/images/Config.6.png)

As shown in 
https://github.com/microsoft/Learn-LTI/blob/main/docs/CONFIGURATION_GUIDE.md#Moodle-LMS

**Comment by leestott** [comment] 2021-03-15 13:17
@coachsbansal Thanks for sharing the Function ->GetUserDetails Logs which you obtained from Azure Portal https://portal.azure.com Function -> GetUserDetails -> Monitor

As you can see the issue is because you are using a Self Signed Certificate and NOT a trusted certification provider SSL. You need to utilize a fully trusted SSL 

![FunctionGetUserDetails](https://user-images.githubusercontent.com/2511341/111159286-d7f6e980-8590-11eb-8def-79325c70becf.png)

**Comment by coachsbansal** [comment] 2021-03-15 13:47
Thank you Lee, Let me check the solution shared by you and revert.

regards

**Comment by leestott** [comment] 2021-03-16 14:04
Hi @coachsbansal 

So thanks for running troubleshooting process from Azure portal on the functions 

![Innovation Details](https://user-images.githubusercontent.com/2511341/111321851-3c34ae80-8660-11eb-830f-9dee8678e12e.png)

So the issue is a 401 unauthorized access we have seen this before with Moodle and the issue is relation to the Apache Config on Moodle. 

## Fix 
An Unauthorized (401) Exception occurred when access the Moodle's LTI services.
/mod/lti/services.php/CourseSection/39/bindings/2/memberships

### The problem came from the Apache Config.

### Solution
Make the following changes to the httpd.conf file or alternatively in the vhosts file 

SetEnvIf Authorization "(.*)" HTTP_AUTHORIZATION=$1
SetEnvIf Content-Type "(.*)" HTTP_CONTENT_TYPE=$1
SetEnvIf Accept "(.*)" HTTP_ACCEPT=$1

## References 
See: https://stackoverflow.com/a/47031629
https://moodle.org/mod/forum/discuss.php?d=389429

**Comment by leestott** [comment] 2021-03-18 14:23
@coachsbansal could you confirm if adding the changes to httpd.conf worked?

**Comment by coachsbansal** [comment] 2021-03-18 14:32
Hi @leesott 


> @coachsbansal could you confirm if adding the changes to httpd.conf worked?

Hi @leestott sorry for delay in response. Yes issue got resolved. Thanks for you and your team for quick response.

**Comment by leestott** [comment] 2021-03-18 21:22
@coachsbansal thanks for the confirmation I will close this issue but again any queries please reach out and we would love to hear how your institution progresses and uses the LTI Application

**Closed by leestott** 2021-03-18 21:22 UTC

**Comment by coachsbansal** [comment] 2021-03-19 01:43
Sure, thank you once again.
