### ISSUE TITLE
Link between Moodle and Microsoft learn is not working Moodle 3.8 (Legacy)

### ISSUE THREAD

**Issue by RaedTaha** [microsoft/Learn-LTI#165] opened 2021-11-09 06:43 UTC
We managed to deploy Microsoft Learn LTI on Azure and configured the LTI 1.1 and LTI 1.3 on our Moodle LMS.

After that, we followed the instruction in the educator guide, and we managed to create Microsoft Learn course on Moodle but unfortunately the migration /link between Moodle and Microsoft learn is not working.
pressing the link navigates to an error message as follows;

"Could not validate request"

I hope you can support us to troubleshoot the issue
 Best

**Comment by leestott** [comment] 2021-11-09 07:29
@RaedTaha 

LTI Application does not load error: {"Message":"Could not validate request"}
This issue is typically related to one of the following:

Please see https://github.com/microsoft/Learn-LTI/blob/main/docs/TROUBLESHOOTING.md this is a known setup/config issues which need to address with your Moodle Implementation. 

Check if you have a valid 3rd Party Signed SSL. This services requires a valid 3rd party SSL certificate, self signed SSL certificates are not valid. Please ensure your service is using https:// with a valid SSL certification.
Check the Launch URL, please make sure that all the fields are correctly filled while registering the tool and filling tool's platform registration page. See https://github.com/microsoft/Learn-LTI/blob/main/docs/CONFIGURATION_GUIDE.md
Check the Azure Function/Azure Logs see https://github.com/microsoft/Learn-LTI/blob/main/docs/TROUBLESHOOTING.md#azure-functions-tracing

There are instructions for setting up a SSL in the guide also 
Or 

LTI Application does not load error: {"Message":"Could not validate nonce."}
If you receive a browser message: {"Message":"Could not validate nonce."}

We have seen this is an intermittent issue, it usually happens if the user is trying to replay an old call or if the nonce and state value don't match. If the user simply refreshes the browser the page will load.

**Comment by RaedTaha** [comment] 2021-11-10 09:15
Dear @leestott,
We went over all steps and all seems correctly configured. on Azure no errors are logged neither exceptions.
Unfortunately, we still have the same error message, any other ideas?  

Thanks in advanced!
Raed & Nael

**Comment by leestott** [comment] 2021-11-10 11:15
@RaedTaha 

There must be error logged in the function or browser stack trace 

Troubleshooting Errors

Azure Functions Tracing

This should provide details related to the execution context and state of the function execution when it has returned and error

Goto your Resource Group inside Azure and select Function App matching users-XXXXXXX.
Select Functions Blade in Left Hand Pane.
Select GetUserDetails afterwards.
Choose Monitor Blade in LHP and you should see the Invocation Traces.
Clicking on the failing trace should provide more details related to Server logs for that function invocation to help you.
Failures (Exceptions) in App Insights
Go to your Resource Group inside Azure and select Application Insights resource matching users-XXXXXXX.
Select Failures Blade in LHP and then choose Exceptions Tab.

The subsequent screen should indicate any exceptions that were thrown as a part of function execution and should provide more insights into what might've gone wrong.

We'd request you to please share the above details with us in order for us to be able to help you in a better way. Since the details might contain some private information as well. Please feel free to reach out to us via email at learnlti@microsoft.com.

Failure is in Users Function App

Function app which is not being able to find the user (signed-in via AAD) enrolled into the current course.
Please check that the return code for the API in the Chrome DevTools network tab to see the stack trace

**Comment by leestott** [comment] 2021-11-26 15:19
@RaedTaha 

Thanks for the call and screen share So we have been doing some further investigations and the Moodle team confirmed that 3.8 is no longer official supported 

The Moodle team were also unsure if 3.8 would fully work and agreed the ZTEST should validate the Moodle backend. ZTest link: https://ztest.cengage.info/ztest/ 

Here are the steps for installing ZTest tool: https://tracker.moodle.org/browse/MDL-67072 (under "you can install for example ZTest by following the steps":)

They did stress you should think about upgrading your Moodle implementation to a version higher than Moodle 3.9

The most recent long-term support release (LTS) version is Moodle 3.9.
Version	Release status	Initial release	General support ends	Security support ends
3.9 (LTS)	Current security	15 June 2020	10 May 2021	8 May 2023
3.10	Current security	9 November 2020	8 November 2021	9 May 2022
3.11	Current stable	17 May 2021	9 May 2022	14 November 2022
4.0	Future stable	January 2022	14 November 2022	8 May 2023

**Comment by leestott** [comment] 2021-12-06 10:45
@RaedTaha I will close this issue as its a known issue with Moodle 3.8 which has now been depreciated please update your Moodle Environment to supported version.

**Closed by leestott** 2021-12-06 10:45 UTC
