### ISSUE TITLE
After an Activity/Resource is Added in Moodle, unable to proceed to Customize, Review and Publish the Assignment

### ISSUE THREAD

**Issue by chintan-patel-za** [microsoft/Learn-LTI#109] opened 2021-01-08 15:36 UTC
Hi.

I followed all the steps to setup the Microsoft Learn LTI via Moodle. Everything was successful up to this step:

https://github.com/microsoft/Learn-LTI/blob/main/docs/USER_GUIDE.md#customize-review-and-publish-the-assignment

I am unable to customize, review and publish the assignment. The page just keeps loading. I've tried multiple browsers, restarted the Azure VMs, cleared cache/cookies, etc but the page has been "loading assignment" for hours and hours.

Please advise what could be the issue? Video attached/below.

https://user-images.githubusercontent.com/72276558/104033232-f1b63200-51d7-11eb-9048-d4b979b4ada8.mp4

**Comment by adbindal** [comment] 2021-01-08 18:43
Hi @chintan-patel-za,

Thanks a lot for reporting the issue. The issue is definitely with either the assignments API or Users API returning some unknown response due to which client is landing itself to this situation. In order to better understand the behavior, could you please share that the return code for all API calls that are made when we open this page . You'd need to open Chrome DevTools, goto network tab and copy all as HAR to share it with us.


## Troubleshooting
### Azure Function Traces
This should provide details related to the execution context and state of the function execution when it would've returned the error.

### Failures (Exceptions) in App Insights
* We'd need to go to the Azure function which might be at fault here. 
* Select Failures Blade in LHP and then choose Exceptions Tab.
* The subsequent screen should indicate any exceptions that were thrown as a part of function execution and should provide more insights into what might've gone wrong on server when executing failing api.

We'd request you to please share the above details with us in order for us to be able to help you in a better way. Since the details might contain some private information as well. 

> Please feel free to reach out to us via email at learnlti@microsoft.com in order to help us provide deeper support to this problem.

**Comment by chintan-patel-za** [comment] 2021-01-10 11:43
Hi @adbindal , I sent an email yesterday to the specified email address with the required information. Hope to hear a response soon.

**Comment by leestott** [comment] 2021-02-09 13:31
@chintan-patel-za 
![image](https://user-images.githubusercontent.com/2511341/107370420-dd1cd080-6ada-11eb-988e-76a7ac6423ee.png)
From the logs, It seems like the users/me call is failing with response code 0. There might be some issue on the corresponding Azure Function (it is Users FunctionApp with GetUserDetails endpoint inside Azure).

Our troubleshooting recommendation should allow you to get some insights on what might be going wrong on the server 

See this older ticket which talks about similar troubleshooting https://github.com/microsoft/Learn-LTI/issues/55#issuecomment-694431630

Does this resolve your issue

**Comment by leestott** [comment] 2021-03-23 00:24
@chintan-patel-za this issue has been open with no new comments for a while. We close this issue but if your still having issues please look at Troubleshooting guide.

**Closed by leestott** 2021-03-23 00:24 UTC
